"""add seeking descr


Revision ID: 542820fa02bf
Revises: f5bdbe5dfe04
Create Date: 2020-07-02 02:01:25.398462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542820fa02bf'
down_revision = 'f5bdbe5dfe04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
